export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCT_NAME = "SEARCH_PRODUCT_NAME";
export const GET_CATEGORIES = "GET_CATEGORIES"
export const POST_PRODUCT ="POST_PRODUCT"
export const SET_FILTERS ="SET_FILTERS"
export const GET_FILTERED_CATEGORIES = "GET_FILTERED_CATEGORIES";

